package com.inesv.ecchain.kernel.peer;


public enum PeersEvent {
    BLACKLIST, UNBLACKLIST, DEACTIVATE, REMOVE,
    DOWNLOADED_VOLUME, UPLOADED_VOLUME, WEIGHT,
    ADDED_ACTIVE_PEER, CHANGED_ACTIVE_PEER,
    NEW_PEER, ADD_INBOUND, REMOVE_INBOUND, CHANGED_SERVICES
}
